#!/usr/bin/env node
// Writes apps/web/.env.local for local development from `supabase status` plus freshly generated
// app secrets. Values are written straight to the file and never printed.
import { spawnSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const target = resolve(repoRoot, "apps/web/.env.local");

const status = spawnSync(process.execPath, [resolve(repoRoot, "scripts/supabase.mjs"), "status", "-o", "env"], {
  cwd: repoRoot,
  encoding: "utf8",
});
if (status.status !== 0) {
  console.error("`supabase status` failed — is the local stack running? (npm run db:start)");
  process.exit(1);
}
const local = Object.fromEntries(
  status.stdout
    .split(/\r?\n/)
    .map((line) => /^([A-Z_]+)="?(.*?)"?$/.exec(line.trim()))
    .filter(Boolean)
    .map((m) => [m[1], m[2]]),
);

// Keep previously generated app secrets so existing encrypted rows stay readable.
const previous = existsSync(target)
  ? Object.fromEntries(
      readFileSync(target, "utf8")
        .split(/\r?\n/)
        .map((line) => /^([A-Z_]+)=(.*)$/.exec(line))
        .filter(Boolean)
        .map((m) => [m[1], m[2]]),
    )
  : {};

const values = {
  NEXT_PUBLIC_SUPABASE_URL: local.API_URL,
  NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: local.PUBLISHABLE_KEY ?? local.ANON_KEY,
  SUPABASE_SECRET_KEY: local.SECRET_KEY ?? local.SERVICE_ROLE_KEY,
  APP_URL: previous.APP_URL ?? "http://localhost:3000",
  APP_ENC_KEY: previous.APP_ENC_KEY ?? randomBytes(32).toString("base64"),
  APP_ENC_KEY_VERSION: previous.APP_ENC_KEY_VERSION ?? "1",
  CRON_SECRET: previous.CRON_SECRET ?? randomBytes(32).toString("base64url"),
  GOOGLE_CLIENT_ID: previous.GOOGLE_CLIENT_ID ?? "",
  GOOGLE_CLIENT_SECRET: previous.GOOGLE_CLIENT_SECRET ?? "",
  RESEND_API_KEY: previous.RESEND_API_KEY ?? "",
  EMAIL_FROM: previous.EMAIL_FROM ?? "gnouht hub <noreply@gnouht.space>",
};

const missing = Object.entries(values)
  .filter(([key, value]) => !value && (key.startsWith("NEXT_PUBLIC") || key === "SUPABASE_SECRET_KEY"))
  .map(([key]) => key);
if (missing.length) {
  console.error(`Could not read ${missing.join(", ")} from supabase status`);
  process.exit(1);
}

writeFileSync(
  target,
  `# Generated by scripts/dev-env.mjs for local development — never commit.\n${Object.entries(values)
    .map(([key, value]) => `${key}=${value}`)
    .join("\n")}\n`,
  { mode: 0o600 },
);
console.log(`wrote ${target} (${Object.keys(values).join(", ")})`);
